language: python
python: 2.7
services: redis-server
env:
    - TOX_ENV=py27
    - TOX_ENV=flake8
install:
    - if [[ $ACTION != loadtest ]]; then pip install tox; fi
script:
    - cp boto ~/.boto
    - if [[ $ACTION != loadtest ]]; then tox -e $TOX_ENV; fi
    - if [[ $ACTION == loadtest ]]; then make loadtest-check; fi
after_success:
    # Report coverage results to coveralls.io
    - pip install coveralls
    - coveralls
